const json = (schema: unknown) => ({ "application/json": { schema } });
const reference = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const nullableString = { type: ["string", "null"] };
const decimal = { type: ["string", "null"], pattern: "^\\d+(\\.\\d{1,2})?$", description: "十进制字符串，最多两位小数；显式 null 清空，省略保留。体重 >0 且 <=99999.99，体脂 0–100。" };
const date = { type: "string", format: "date" };
const operationId = { type: "string", pattern: "^[a-zA-Z0-9-]{8,120}$", description: "每次新操作唯一；同请求重试复用，不同内容或令牌不能复用。" };
const period = { type: "string", enum: ["daytime", "evening"] };
const timezone = { ...nullableString, description: "新记录省略时每次自动采用系统时区：X-Formward-Timezone 优先，否则读取 Formward 服务系统时区。明确提供可覆盖默认值，审核页仍可修改。建议固定偏移 +08:00（网页 GMT+8／东八区），界面选择项仅含 GMT-12 至 GMT+14 的整数小时，兼容已有非整点偏移与 IANA 名称。已有记录省略保留，显式 null 保持未指定／清空。历史修改仅通过 PeriodEdit 或 SaveRecord 的 timezone 生效，保留当地钟点；只有原准确时间才重算 UTC。" };
const systemTimezoneHeader = { name: "X-Formward-Timezone", in: "header", required: false, schema: { type: "string" }, description: "客户端每次读取设备系统时区，传 +08:00 等固定偏移或 IANA 名称；pnpm ai:request 自动发送。未传则采用 Formward 服务所在系统时区。只作为新记录默认值，重试保留第一次预览的时区。" };
const editProperties = { recordId: { type: "string", description: "修改已有字段、来源或时区时明确指定；须与 version 同时提供。" }, version: { type: "string", format: "date-time", description: "GET 返回的 updatedAt，原样提交。" }, weightKg: decimal, bodyFatPercent: decimal, fasting: { type: ["boolean", "null"], description: "晨间仅 true；旧非空腹／未知晨间只读，晚间固定 false。" }, deviceLabel: { ...nullableString, minLength: 1, maxLength: 300, description: "用户提供的来源名称，新实测必填；既有记录省略保留。" }, timezone };
const metric = { type: "string", enum: ["weightKg", "bodyFatPercent"] };
const responses = {
  "200": { description: "本账号结果；提交只产生预览。items 每条 status=confirmed 才已保存，counts 给出完整审核进度。", content: json(reference("Operation")) },
  "400": { description: "无效字段、日期、数值、空腹条件或已有不可估算项。", content: json(reference("Error")) },
  "401": { description: "令牌无效、过期或撤销。", content: json(reference("Error")) },
  "403": { description: "只读令牌不能提交操作。", content: json(reference("Error")) },
  "404": { description: "操作不存在或属于其他账号。", content: json(reference("Error")) },
  "409": { description: "operationId 已用于不同内容或令牌。", content: json(reference("Error")) },
  "500": { description: "服务暂不可用；不返回数据库内部信息。", content: json(reference("Error")) },
};
export const measurementOpenApi = {
  openapi: "3.1.0", info: { title: "Formward 身体记录 API", version: "1.2.0", description: "身体记录查询、批量录入、历史／来源／时区修改和单项估算。新记录自动采用当次系统时区，审核页可修改。令牌有效期 30 天；所有写入先生成 15 分钟预览，在一个网页登录审核页逐行或整批确认。无 API 确认入口；兼容 save_day 和独立 estimate_cell。" },
  servers: [{ url: "/api/v1" }], security: [{ bearerAuth: [] }],
  paths: {
    "/measurements": { get: { operationId: "queryMeasurements", summary: "查询本账号记录、来源、摘要、趋势与逐日分析", parameters: [
      systemTimezoneHeader, { name: "from", in: "query", schema: date }, { name: "to", in: "query", schema: date },
      { name: "choices", in: "query", schema: { type: "string" }, description: "URL 编码 JSON：{\"YYYY-MM-DD:daytime\":\"recordId\"}。必须是本账号对应时段实测，仅影响本次分析。" },
    ], responses: { ...responses, "200": { description: "记录与逐日／趋势按区间筛选；摘要读取全历史，与网页一致。未知为 null，估计不进入实测摘要。体重单位 kg、体脂 %、体脂差值为百分点。", content: json({ type: "object", required: ["context", "records", "sources", "analyses", "units", "dates"], properties: { context: { type: "object", required: ["timezone", "timezoneLabel", "localDate"], properties: { timezone: { type: "string" }, timezoneLabel: { type: "string" }, localDate: date }, description: "本次系统时区与当地日期；客户端请求头优先，否则读取服务系统。" }, records: { type: "array", items: reference("Measurement") }, sources: { type: "array", items: { type: "string" } }, dates: { type: "array", items: { type: "object" } }, analyses: { type: "object", description: "weightKg 和 bodyFatPercent 各含 summary、trend、days；同用网页业务函数。" }, units: { type: "object" }, range: { type: "object" }, rules: { type: "string" } } }) } } } },
    "/measurement-operations": { post: { operationId: "submitMeasurementOperation", summary: "提交跨日批量或兼容单日／单项预览，返回一个审核链接", parameters: [systemTimezoneHeader], description: "batch 最多 100 条、64 KiB。新实测来源必填，晨间明确 fasting:true。不同已知值需要 recordId+version；重复跳过、缺项补充。批量业务错误留在对应行，阻止整批保存，有效行仍可单独保存；网页支持修改并更新预览。单行确认立即保存，取消剩余不撤销已保存行。新记录省略时区时自动采用当次系统时区，明确值或 null 优先；已有记录省略保留。未知测量时间不虚构。估算只用已保存实测。", requestBody: { required: true, content: { "application/json": { schema: { oneOf: [reference("Batch"), reference("SaveDay"), reference("EstimateCell")] }, examples: { fictionalBatch: { summary: "虚构格式示例，不代表用户数据", value: { kind: "batch", operationId: "fictional-example-0001", items: [{ kind: "save_record", date: "2024-04-04", period: "daytime", weightKg: "70.20", bodyFatPercent: "20.10", fasting: true, deviceLabel: "虚构体重秤", timezone: "+08:00" }, { kind: "save_record", date: "2024-04-05", period: "evening", bodyFatPercent: "20.30", deviceLabel: "虚构体重秤" }] } } } } } }, responses: { ...responses, "413": { description: "请求超过 64 KiB。" }, "415": { description: "需要 application/json。" } } } },
    "/measurement-operations/{id}": { get: { operationId: "getMeasurementOperation", summary: "查询本账号操作预览与最终状态", parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses } },
  },
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", description: "在网页 AI 接入创建的可撤销令牌，不是模型 API Key。" } }, schemas: {
    PeriodEdit: { type: "object", additionalProperties: false, properties: editProperties },
    SaveRecord: { type: "object", additionalProperties: false, required: ["kind", "date", "period"], properties: { kind: { const: "save_record" }, date, period, ...editProperties } },
    BatchEstimate: { type: "object", additionalProperties: false, required: ["kind", "date", "period", "metric"], properties: { kind: { const: "estimate_cell" }, date, period, metric } },
    Batch: { type: "object", additionalProperties: false, required: ["kind", "operationId", "items"], properties: { kind: { const: "batch" }, operationId, items: { type: "array", minItems: 1, maxItems: 100, items: { oneOf: [reference("SaveRecord"), reference("BatchEstimate")] } } } },
    SaveDay: { type: "object", additionalProperties: false, required: ["kind", "date", "operationId", "periods"], properties: { kind: { const: "save_day" }, date, operationId, timezone: { ...timezone, description: "兼容旧请求的新记录默认时区；省略自动采用当次系统时区，显式 null 保持未指定。不改变既有记录时区；历史修改须在对应时段提供 timezone。" }, periods: { type: "object", minProperties: 1, additionalProperties: false, properties: { daytime: reference("PeriodEdit"), evening: reference("PeriodEdit") } } } },
    EstimateCell: { type: "object", additionalProperties: false, required: ["kind", "date", "operationId", "period", "metric"], properties: { kind: { const: "estimate_cell" }, date, operationId, period, metric } },
    Measurement: { type: "object", properties: { id: { type: "string" }, recordDate: date, period, weightKg: decimal, bodyFatPercent: decimal, deviceLabel: nullableString, fasting: { type: ["boolean", "null"] }, recordKind: { enum: ["observed", "estimated"] }, updatedAt: { type: "string", format: "date-time" }, entryChannel: nullableString, sourceLocalTime: { type: "string" }, timezone: nullableString, timezoneLabel: { type: "string", description: "按测量日期／已保存准确偏移显示 GMT+8（东八区）等标签；未知显示未指定。" }, utcOffsetMinutes: { type: ["integer", "null"] }, timePrecision: { type: "string" }, estimation: { type: ["object", "null"] }, estimateExplanation: { type: ["object", "null"] } } },
    Preview: { type: "object", description: "date、kind、canConfirm、message、rows；defaultTimezone 保留首次预览采用的系统默认时区。rows 含 period、state(new/edit/supplement/duplicate/conflict/invalid/estimate)、before、after、message、replacedEstimates。估算含 explanation。批量 items 保留行草稿与结果。" },
    ReviewDraft: { type: "object", description: "save_record 或 estimate_cell 候选；批量业务错误原样保留，故日期／数值可能尚未有效，查看 preview.canConfirm 和行内错误。", properties: { ...editProperties, kind: { enum: ["save_record", "estimate_cell"] }, date: { type: "string" }, period, metric, weightKg: nullableString, bodyFatPercent: nullableString, version: nullableString } },
    ReviewItem: { type: "object", properties: { id: { type: "string", description: "本次审核内稳定标识" }, status: { enum: ["pending", "confirmed", "cancelled", "skipped"] }, input: reference("ReviewDraft"), originalInput: reference("ReviewDraft"), preview: reference("Preview"), editedBy: { type: "object" }, result: { type: "object", description: "已确认行的 saved、message、confirmedAt" } } },
    Operation: { type: "object", required: ["id", "status", "revision", "items", "counts", "preview", "confirmationUrl", "expiresAt"], properties: { id: { type: "string" }, operationId: { type: "string" }, status: { enum: ["pending", "partially_confirmed", "confirmed", "completed", "cancelled", "expired"], description: "confirmed 全部待保存行已保存；partially_confirmed 部分保存且尚有待处理；completed 混合终态或全部跳过。逐行结果以 items.status 为准。" }, revision: { type: "integer", minimum: 1, description: "网页修改／刷新／确认／取消递增，防止跨页面覆盖" }, items: { type: "array", items: reference("ReviewItem") }, counts: { type: "object", properties: Object.fromEntries(["total", "saved", "cancelled", "skipped", "pending", "issues"].map(key => [key, { type: "integer", minimum: 0 }])) }, confirmationUrl: { type: "string", format: "uri" }, confirmationPath: { type: "string" }, expiresAt: { type: "string", format: "date-time" }, createdAt: { type: "string", format: "date-time" }, confirmedAt: { type: ["string", "null"] }, repeated: { type: "boolean" }, preview: reference("Preview"), result: { type: ["object", "null"], properties: { message: { type: "string" }, saved: { type: "integer" } } } } },
    Error: { type: "object", properties: { error: { type: "object", properties: { code: { type: "string" }, message: { type: "string" } } } } },
  } },
};
